### PR TITLE
Add a 'run' flag to WamTransportData to indicate if transport is currently running

### PR DESCRIPTION
**Pull request by boourns**
Pretty self-explanatory.  I could see the 'flags' being used to also indicate if transport is paused as a third state, but didn't implement that here.

This PR sits on top of #65, that commit's here as well.

### CODE REVIEW

**Review by owengc — CHANGES_REQUESTED** [review]
I'm not opposed to adding a property to indicate host sequencer state, but to me this particular choice doesn't fit with the existing `WamEvent` properties. Please see my comment below for more detail.

Thanks for tending to `WamEventRingBuffer` btw..there are tests which should be updated as well though:
https://github.com/53js/webaudiomodule/blob/master/packages/sdk/__test__/WamEventRingBuffer.spec.ts

**Comment by boourns** [comment]
Yeah.. you're right @owengc.  I had it implemented as a boolean in the other Transport implementation anyways.  Not sure I went with this 😄 

Fixed now, tests fixed as well

**Comment by boourns** [comment]
Actually, please hold off reviewing for a bit.  With this change, transport events are no longer distributed to the worklet in my host so I'm investigating.

**Comment by boourns** [comment]
.. ok, I figured out my issue and it was unrelated, this can be reviewed 🟢

**Review by owengc — APPROVED** [review]
Thanks for making those changes @boourns ! I'll go ahead merge this and handle updating the tests for WamEventRingBuffer on my end

**Pull request merged**
